name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          echo "Current directory:"
          pwd
          echo "Files here:"
          ls -la
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt || echo "Skipping requirements"

      - name: Run script
        run: python hello.py